# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 368be390d38091b6503f7c186f4088bcb4cf709ea72b88176839397465a5f555ed33264540e36734d4490b9be211388c1a6696e8187e7d313de232fbfbae4b0f

test:
  secret_key_base: b111b1b04baccce7ba64396040b48da7755aaaf00b73912508dd4eaa33bce44b0ccd21fcb471761f07932d9b09a60ff8ae73d428d805f0ee770a10ca5b8366bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
